# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: WSABuilds.WSABuildsManager
PackageVersion: 0.2.2
MinimumOSVersion: 10.0.19045.0
InstallerType: nullsoft
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://github.com/IamAzmathullaShaikh/WSABuilds/releases/download/v0.2.2/WSABuildsManager-Setup-0.2.2-x64.exe
    InstallerSha256: "887443bad0aeb3eec04ff367b4768edad2cc0e1b2fcd6b9b255f5bfd3181466a"
    Scope: user
ManifestType: installer
ManifestVersion: 1.6.0
